version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - db-data:/data
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
